[project]
name = "github-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "flask>=3.1.2",
    "flask-jwt-extended>=4.7.1",
    "flask-sqlalchemy>=3.1.1",
    "langchain>=1.2.8",
    "langchain-ollama>=1.0.1",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]
